version : '3'
services:
  local-mypage-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mypage
      MYSQL_USER: mypage
      MYSQL_PASSWORD: mypage
      LANG: C.UTF-8
    ports:
      - "3306:3306"
