version : '3'
services:
  local-mypage-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mypage
      MYSQL_USER: mypage
      MYSQL_PASSWORD: mypage
      LANG: C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - "./db-script/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db-script/users.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./db-script/budgets.sql:/docker-entrypoint-initdb.d/3.sql"
      - "./db-script/job_postings.sql:/docker-entrypoint-initdb.d/4.sql"
