openapi: 3.0.1
info:
  title: JPro My Page API
  description: API for JPro My Page
  version: 1.0.0
paths:
  /job-posting:
    get:
      tags:
        - JobPosting
      operationId: getJobPostings
      summary: Get job postings
      description: Returns the job postings added by admins. Allows filtering by different criteria.
      responses:
        '200':
          description: A JSON array of job postings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobPostingsResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
    post:
      tags:
        - JobPosting
      operationId: createJobPosting
      summary: Create job postings
      description: Returns the job posting added.
      requestBody:
        description: Job posting to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobPosting'
      responses:
        '200':
          description: The added job posting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobPostingResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
components:
  schemas:
    Customer:
      type: string
      description: The name of a customer
      example: "Skatteetaten"
    JobPosting:
      type: object
      properties:
        title:
          type: string
          description: The title of a job posting
          example: "Software Engineer"
        customer:
          $ref: '#/components/schemas/Customer'
        deadline:
          type: string
          format: date-time
          description: The deadline for submitting applications
          example: "2024-10-09T12:00:00+02:00"
        description:
          type: string
          description: The description of the job posting
          example: "Skatteetaten leter etter en dyktig Kotlin-utvikler"
        tags:
          type: array
          description: A list of tags that can be used to filter relevant job postings
          example: ["Java", "Kotlin", "React"]
          items:
            $ref: '#/components/schemas/Tag'
        files:
          type: array
          items:
            type: string
        links:
          type: array
          items:
            type: string
      required:
        - title
        - customer
        - deadline
        - description
        - tags
        - files
        - links
    JobPostingResponse:
      allOf:
        - $ref: '#/components/schemas/JobPosting'
        - type: object
          properties:
            id:
              type: string
              description: The unique identifier for the job posting
              example: "123"
          required:
            - id
    JobPostingsResponse:
      type: array
      description: List of job postings that match the provided filters
      items:
        $ref: '#/components/schemas/JobPostingResponse'
    Tag:
      type: string
      description: A tag that describes e.g. a technology or method used in the project
      example: "Kotlin"