runtime: java17
service: api

#manual_scaling:
#  instances: 1

#automatic_scaling:
#  min_instances: 1
#  max_instances: 1

basic_scaling:
  max_instances: 1
  idle_timeout: 10m

handlers:
- url: /api/.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"
  SPRING_LIQUIBASE_ENABLED: "true"
  SPRING_LIQUIBASE_CHANGE_LOG: "classpath:/db/changelog/db.changelog-root.yaml"
  GOOGLE_CLIENTID: "365277685106-agts9g8tvljvdflgqottt52ujp8p989d.apps.googleusercontent.com"
  GCP_PROJECTID: "my-page-jpro-test"
  SLACK_HYTTEKANAL_ID: "C05HJ96ACLA"
