runtime: java17
service: api

#manual_scaling:
#  instances: 1

#automatic_scaling:
#  min_instances: 1
#  max_instances: 1

basic_scaling:
  max_instances: 1
  idle_timeout: 10m

handlers:
- url: /api/.*
  secure: always
  redirect_http_response_code: 301
  script: auto


#readiness_check:
#  path: "/actuator/health"
#  check_interval_sec: 10
#  timeout_sec: 4
#  failure_threshold: 2
#  success_threshold: 2
#
#liveness_check:
#  path: "/actuator/health"
#  check_interval_sec: 30
#  timeout_sec: 4
#  failure_threshold: 3
#  success_threshold: 1

env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"
  SPRING_LIQUIBASE_ENABLED: "false"
  SPRING_LIQUIBASE_CHANGE_LOG: "classpath:/db/changelog/db.changelog-root.yaml"
  GOOGLE_CLIENTID: "365277685106-agts9g8tvljvdflgqottt52ujp8p989d.apps.googleusercontent.com"
  GCP_PROJECTID: "my-page-jpro-test"
  GCS_BUCKET_NAME: "tavle-cropped-test"
  GCS_JOBPOSTINGS_BUCKET_NAME: "utlysninger-dokumenter-test"
  SLACK_HYTTEKANAL_ID: "C05HJ96ACLA"
