name: APITest
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Navn på branch som skal deployes til test'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch_name }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'
          cache: 'maven'
      - name: Perform build
        run: |
          ./mvnw -pl my-page-api -am package
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: my-page-api/target/my-page-api-0.0.1-SNAPSHOT.jar
      - name: Upload app.yaml
        uses: actions/upload-artifact@v4
        with:
          name: app.yaml
          path: my-page-api/src/main/appengine/app.yaml
  deploy-test:
    needs: build
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Download jar
        uses: actions/download-artifact@v3
        with:
          name: jar
      - name: Download app.yaml
        uses: actions/download-artifact@v3
        with:
          name: app.yaml
      - name: Deploy to test
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: my-page-jpro-test
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: app deploy my-page-api-0.0.1-SNAPSHOT.jar --appyaml=app.yaml
  remove-old-versions-test:
    needs: deploy-test
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: my-page-jpro-test
      - run: gcloud app versions list --service=api --filter="version.createTime < $(date -Idate --date='last month')" --format="value(version.id)" | xargs --no-run-if-empty gcloud app versions delete
