name: Deploy api
on:
  - push
  - workflow_dispatch
jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17'
          cache: 'maven'
      - name: Perform build
        run: |
          ./mvnw -DskipTests package
        working-directory: ./my-page-api
      - name: Deploy to app engine
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: my-page-jpro-test
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: app deploy my-page-api/target/my-page-api-0.0.1-SNAPSHOT.jar --appyaml=my-page-api/src/main/appengine/app.yaml
