name: Deploy app
on:
  push:
    branches:
      - main
      - deploy-with-actions
    paths:
      - '.github/**'
      - 'my-page-app/**'
  workflow_dispatch:
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: my-page-app/package-lock.json
      - name: Perform build
        run: |
          npm ci
          npm run build
        working-directory: ./my-page-app
      - name: Deploy to test
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: my-page-jpro-test
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: app deploy my-page-app/app.yaml
      - name: Deploy to prod
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: my-page-jpro
          APPLICATION_CREDENTIALS: ${{ secrets.PROD_GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: app deploy my-page-app/app.yaml
