name: email-validator
on:
  push:
    branches:
      - main
      - smtp-pubsub-pipeline
    paths:
      - 'email-validator/**'
  workflow_dispatch:

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: my-page-jpro-test
      - run: |-
          gcloud functions list
      - run: |-
          gcloud functions deploy email-validator --gen2 --region=europe-west1 --runtime=java17 --source=./email-validator --entry-point=EmailValidatorFunction --trigger-topic=raw-email
