name: smtp-to-pubsub
on:
  push:
    branches:
      - main
      - smtp-pubsub-pipeline
    paths:
      - 'smtp-to-pubsub/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: my-page-jpro-test
      - run: |-
          gcloud auth configure-docker europe-west1-docker.pkg.dev
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./
          file: ./smtp-to-pubsub/Dockerfile
          push: true
          tags: europe-west1-docker.pkg.dev/my-page-jpro-test/images/smtp-to-pubsub:${{ github.sha }}
  deploy-test:
    needs: build
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Deploy to test
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: my-page-jpro-test
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: compute instances update-container smtp-to-pubsub --zone=europe-west1-c --container-image=europe-west1-docker.pkg.dev/my-page-jpro-test/images/smtp-to-pubsub:${{ github.sha }}
