name: update-raw-email-message-schema
on:
  push:
    branches:
      - main
      - smtp-pubsub-pipeline
    paths:
      - 'schemas/src/main/resources/avro/raw-email-message.avsc'
  workflow_dispatch:

jobs:
  update-schema-test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: my-page-jpro-test
      - name: Commit schema to test
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: my-page-jpro-test
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: pubsub schemas commit raw-email --type avro --definition-file schemas/src/main/resources/avro/raw-email-message.avsc
